@startuml Class Diagram

abstract class Row{
    -stats()
}
class Controller{
    -model_
    -view_
}
abstract class Model{
    #save()
    #get_Row()
}
class ModelDB{
    -db_
}
class KeyWords{
    -video_id_
    -key_word_id_
}

class View{
    -container_
    #set_up()
}
class Video {
    #video_id_
    #episode_number_
    #key_word_ids_
    #title_
    #state
    #publication_date_
    #notes_
}


class Test

Controller *-- Model

Controller *-- View

Row --> Video

Video o-- KeyWords

Model --> ModelDB


@enduml