@startuml Class Diagram

abstract class Table{
}
class Controller{
    -model_
    -view_
}
abstract class Model{
    #save()
    #get_table()
}
class ModelDB{
    -db_
}
class KeyWords{
    -key_words_list_
    -id_
}

class View{
    -container_
    #set_up()
}
class Video {
    #id_
    #episode_number_
    #title_
    #state
    #publication_date_
    #notes_
}

class VideoFullInfo {
    #key_words_
    #video_

}
class Statistics{
    -table_
    +show_graph()
}
class Test

Controller *-- Model

Controller *-- View

Table --> Video

Table --> KeyWords

Table --> VideoFullInfo

VideoFullInfo o-- Video

VideoFullInfo o-- KeyWords

Model --> ModelDB

Statistics *-- Table

@enduml